PRINT MACRO CHAR
PUSH AX
PUSH DX
MOV DL,CHAR
MOV AH,2
INT 21H
POP DX
POP AX
ENDM

READ MACRO  
PUSH AX
MOV AH,8
INT 21H
POP AX
ENDM    

PRINT_STR MACRO STR
PUSH AX
PUSH DX
MOV DX,OFFSET STR
MOV AH,9
INT 21H 
POP DX
POP AX
ENDM  

READ_DEC MACRO
READZ:
    MOV AH,8
    INT 21H
    CMP AL, 'D'
    JE QUIT
    CMP AL, '0'
    JL READZ
    CMP AL, '9'
    JG READZ
    PRINT AL 
ENDM            

READ_HEX MACRO
READX:
    MOV AH,8
    INT 21H ;INT 21/08 READS KEYBOARD AND AL<- 8-bit ASCII code of keyboard input
    CMP AL,48   ;ASCII OF 0
    JL READX
    CMP AL,57   ;ASCII OF 9
    JLE ZERO_TO_NINE_OR_A_TO_F
    
    CMP AL,64   ;ASCII OF A
    JL READX
    CMP AL,70   ;ASCII OF F
    JG READX
    
    ZERO_TO_NINE_OR_A_TO_F:    ;AL HAS 0-9 OR A-F
    PRINT AL    ;PRINT IT
ENDM


STACK_SEG SEGMENT STACK
DB 30 DUP(?)
STACK_SEG ENDS 

DATA SEGMENT
MSG1 DB "DOSE 2 ARITHMOYS:$"
SPACE DB " $"
MSG2 DB "ATHR=$"
MSG3 DB "DIAF=$" 
MSG4 DB "DIFFERENCE=$"
MINUS DB "-$"
PLUS DB "+$"
EQUAL DB "="
NEWLINE DB 0AH, 0DH, "$"   
ERRORMSG DB "INPROPER INPUT, NO {0,F}$"
DATA ENDS  

CODE SEGMENT 
    ASSUME CS:CODE,SS:STACK_SEG,DS:DATA
    
MAIN PROC FAR
    MOV AX,DATA
    MOV DS, AX 
    START:


;MAIN EDW SUMPLHRWSW-------------




PRINT_STR MSG1
;READ 1o ARITHMO, ARITHMOI MIKROTEROI APO 50H
FIRST_NUM_1ST_DIGIT:
MOV AH,8
INT 21H
CMP AL,'D'
JE QUIT 
CMP AL,53
JGE FIRST_NUM_1ST_DIGIT
CMP AL,48
JL FIRST_NUM_1ST_DIGIT

PRINT AL
MOV BH,AL   
ADD BH,-48  ;BH UPPER HEX OF 1ST NUM


FIRST_NUM_2ND_DIGIT:
MOV AH,8
INT 21H ;INT 21/08 READS KEYBOARD AND AL<- 8-bit ASCII code of keyboard input
MOV BL,AL
CMP AL,'D'
JE QUIT 
CMP AL,48   ;ASCII OF 0
JL FIRST_NUM_2ND_DIGIT
CMP AL,57   ;ASCII OF 9
JLE ZERO_TO_NINE1
    
CMP AL,64   ;ASCII OF A
JL FIRST_NUM_2ND_DIGIT
CMP AL,70   ;ASCII OF F
JG FIRST_NUM_2ND_DIGIT 

ADD BL,-7
    
ZERO_TO_NINE1:    ;AL HAS 0-9

ADD BL,-48  ;BL LOWER HEX OF 1ST NUM
PRINT AL    ;PRINT IT

ROL BH,4
AND BH,11110000b

AND BL,00001111b
ADD BL,BH   ;BL HOLDS 1ST NUMBER (NOT ASCII)


PRINT SPACE

;READ 2o ARITHMO, ARITHMOI MIKROTEROI APO 50H
SECOND_NUM_1ST_DIGIT:
MOV AH,8
INT 21H
CMP AL,'D'
JE QUIT
CMP AL,53
JGE SECOND_NUM_1ST_DIGIT
CMP AL,48
JL SECOND_NUM_1ST_DIGIT

PRINT AL
MOV CH,AL
ADD CH,-48  ;CH UPPER HEX OF 2ND NUM



SECOND_NUM_2ND_DIGIT:
MOV AH,8
INT 21H   
MOV CL,AL
CMP AL,'D'
JE QUIT 
CMP AL,48
JL SECOND_NUM_2ND_DIGIT
CMP AL,57
JLE ZERO_TO_NINE2

CMP AL,64
JL SECOND_NUM_2ND_DIGIT
CMP AL,70
JG SECOND_NUM_2ND_DIGIT

ADD CL,-7

ZERO_TO_NINE2:
ADD CL,-48
PRINT AL

ROL CH,4
AND CH,11110000b  

AND CL,00001111b
ADD CL,CH       ;CL HOLDS 2ND NUMBER (NOT ASCII)


;TWO-DIGIT HEX NUMBERS (8BIT) BL 1ST - CL 2ND
TO_PRESS_ENTER:
MOV AH,8
INT 21H   
CMP AL,'D'
JE QUIT
CMP AL,13
JNE TO_PRESS_ENTER

PRINT_STR NEWLINE
PRINT_STR MSG4

;;;;;;;;;;;;;;;;;;;;;;
;UPOLOGISMOS APOLUTHS TIMHS, APO8HKEUSH STON BH
CMP BL,CL
JL CL_GREATER

MOV BH,BL
SUB BH,CL   ;BH=BL-CL>0
JMP ABSOLUTE_FOUND

CL_GREATER:
MOV BH,CL
SUB BH,BL   ;BH=CL-BL>0

ABSOLUTE_FOUND:     ;BH HAS THE ABSOLUTE VALUE IN 2 HEX DIGITS (8 BITS)
MOV AL,BH
ROR AL,4    ;GET THE 4 MSB BITS IN PLACE
AND AL,00001111b
CMP AL,9
JG FIRST_A_TO_F_ASCII

FIRST_0_TO_9_ASCII:
ADD AL,48
JMP PRINT_1ST

FIRST_A_TO_F_ASCII:
ADD AL,55

PRINT_1ST:
PRINT AL

MOV AL,BH
AND AL,00001111b
CMP AL,9
JG SECOND_A_TO_F_ASCII

SECOND_0_TO_9_ASCII:
ADD AL,48
JMP PRINT_2ND

SECOND_A_TO_F_ASCII:
ADD AL,55

PRINT_2ND:
PRINT AL
 


;MAIN EDW SUMPLHRWSW-------------





PRINT_STR NEWLINE
    

    
    JMP START           ;SYNEXHS LEITOURGIA
    
     QUIT:              ;TERMATISMOS
            MOV AH,4CH	;INT 21/4C EINAI GIA TERMATISMO OPWS PREPEI, EPISTREFONTAS VALUE STON AL
            INT 21H
          
        
MAIN ENDP

PRINT_DEC PROC NEAR	 ;typwnei se dekadiko oti uparxei ston BL se bin
		MOV CX,0
		MOV AX,BX
	DA: MOV DX,0
		MOV BX,10
		DIV BX
		PUSH DX
		INC CX
		CMP AX,0
		JNZ DA
	DA2: POP DX
		ADD DX,30H
		PRINT DL
		LOOP DA2
		RET
PRINT_DEC ENDP 
	
	
PRINT_HEX_DIGITS_FROM_AL PROC NEAR    ;PAIRNEI WS ORISMA TON 8-BIT REGISTER AL
    ;KAI TYPWNEI STHN O8ONH TA HEX PSIFIA TOY(1 'H 2). AN TO PRWTO EINAI MHDEN OPWS p.x.
    ;GIA AL=0000 1010=0Ahex TYPWNEI MONO TO A , ENW AN AL=1001 0101=95H TYPWNEI 95
    ;DEN EPHREAZEI KANENAN KATAXWRHTH!!!
    PUSH AX     
    
    ;MSB HEX PSIFIO
    PUSH AX  ;APO8HKEUSE ORIGINAL ARI8MO
    AND AL,11110000b
    CMP AL,0
    JE LSB_HEX_PSIFIO
    ;MH MHDENIKO TO MSB HEX PSIFIO, TO TYPWNOUME!
    ROR AL,4    ;SHIFT 4 8ESEIS DEKSIA XWRIS KRATOUMENO WSTE NA ER8EI STA MSB TO HEX PSIFIO
    CALL 4_BIT_HEX_TO_ASCII   ;ASCII CODING
    PRINT AL
    
    
    LSB_HEX_PSIFIO:
    POP AX  ;KSANAPARE TON ORIGINAL ARI8MO
    AND AL,00001111b
    CALL 4_BIT_HEX_TO_ASCII   ;ASCII CODING
    PRINT AL
    
 
    POP AX    
    RET
PRINT_HEX_DIGITS_FROM_AL ENDP 	                  
	                  
	
ASCII_TO_HEX_BIT PROC NEAR    ;PAIRNEI WS ORISMA ENAN ARI8MO HEX (0-F) APO TO PLHKTROLOGIO 
    ;POU EINAI STON AL APO8HKEUMENOS SE ASCII KAI EPISTREFEI STON AL TO HEX BIT POU DWSAME
 
    CMP AL,48
    JL ERROR    ;EISODOS EKTOS 0-F
    CMP AL,57
    JG A_TO_F
    
    ;0-9    48-57 DEC STON ASCII PINAKA
    SUB AL,48
    JMP JOB_DONE1
    
    A_TO_F:
    CMP AL,65
    JL ERROR    ;EISODOS EKTOS 0-F
    CMP AL,70
    JG ERROR    ;EISODOS EKTOS 0-F
    
    ;A-F    65-70 DEC STON ASCII PINAKA
    SUB AL,55
    JMP JOB_DONE1
    
    
    ERROR:
    PRINT_STR ERRORMSG 
    
    JOB_DONE1:
    ;APOTELESMA STON AL
    RET
ASCII_TO_HEX_BIT ENDP  


4_BIT_HEX_TO_ASCII PROC NEAR
    ;PAIRNEI WS ORISMA TON AL STH MORFH AL=0000 XXXX
    ;KAI EPISTREFEI TON ASCII TOU STON AL PALI
    ;(DOULEUEI GIA TOUS ASCII TWN 0-9 KAI A-F)
    
    CMP AL,9
    JG A_EWS_F
    
    ;0-9
    ADD AL,48
    JMP DONE
    
    A_EWS_F:
    ;A-F
    ADD AL,55
    
    DONE:
    RET
4_BIT_HEX_TO_ASCII ENDP                         
                         
CODE ENDS
END MAIN