PRINT MACRO CHAR
PUSH AX
PUSH DX
MOV DL,CHAR
MOV AH,2
INT 21H
POP DX
POP AX
ENDM

READ MACRO  
PUSH AX
MOV AH,8
INT 21H
POP AX
ENDM    

PRINT_STR MACRO STR
PUSH AX
PUSH DX
MOV DX,OFFSET STR
MOV AH,9
INT 21H 
POP DX
POP AX
ENDM  

READ_DEC MACRO
READZ:
    MOV AH,8
    INT 21H
    CMP AL, 'D'
    JE QUIT
    CMP AL, '0'
    JL READZ
    CMP AL, '9'
    JG READZ
    PRINT AL 
ENDM            

READ_HEX MACRO
READX:
    MOV AH,8
    INT 21H ;INT 21/08 READS KEYBOARD AND AL<- 8-bit ASCII code of keyboard input
    CMP AL,'D'
    JE QUIT
    CMP AL,48   ;ASCII OF 0
    JL READX
    CMP AL,57   ;ASCII OF 9
    JLE ZERO_TO_NINE_OR_A_TO_F
    
    CMP AL,64   ;ASCII OF A
    JL READX
    CMP AL,70   ;ASCII OF F
    JG READX
    
    ZERO_TO_NINE_OR_A_TO_F:    ;AL HAS 0-9 OR A-F
    PRINT AL    ;PRINT IT
ENDM


STACK_SEG SEGMENT STACK
DB 30 DUP(?)
STACK_SEG ENDS 

DATA SEGMENT
MSG1 DB "DOSE 2 ARITHMOUS:$"
SPACE DB " $"
MSG2 DB "ATHR:$"
MSG3 DB "DIAF=$" 
MINUS DB "-$"
PLUS DB "+$"
EQUAL DB "="
NEWLINE DB 0AH, 0DH, "$"   
ERRORMSG DB "INPROPER INPUT, NO {0,F}$"
DATA ENDS  

CODE SEGMENT 
    ASSUME CS:CODE,SS:STACK_SEG,DS:DATA
    
MAIN PROC FAR
    MOV AX,DATA
    MOV DS, AX 
    START:


;MAIN EDW SUMPLHRWSW-------------




PRINT_STR MSG1
MOV CX,2		;ARITHMOS TWN LOOP POY 8A GINOYN. AN CX=2 => 2 LOOPS
INPUT_READ_LOOP:           ;diavasma input
READ_HEX
CALL ASCII_TO_HEX_BIT
PUSH AX 
LOOP INPUT_READ_LOOP 

PRINT_STR NEWLINE

POP DX  ;2os HEX ARITHMOS STON DL
POP CX  ;1os HEX ARITHMOS STON CL 
PUSH CX
PUSH DX

;ATHROISMA TWN ARITHMWN
PRINT_STR MSG2

ADD DL,CL   ;DL EXEI TO ATHROISMA 
MOV CL,0    ;O CL THA KRATA TIS DEKADES
CMP DL,9
JG DIPSIFIO_ATHROISMA

MONOPSHFIO_ATHROISMA:
ADD DL,48
PRINT DL
JMP ATHROISMA_DONE
               
               
DIPSIFIO_ATHROISMA:
CMP DL,19
JG ISO_H_PANW_APO_20 

DEKA_EWS_19:
PRINT '1'
ADD DL,-10
ADD DL,48
PRINT DL
JMP ATHROISMA_DONE

ISO_H_PANW_APO_20:
PRINT '2'
ADD DL,-20 
ADD DL,48
PRINT DL
               
ATHROISMA_DONE:




PRINT SPACE
PRINT_STR MSG3
;DIAFORA ME PROSHMO 1os - 2os
POP DX
POP CX
CMP CL,DL   ;1os - 2os
JGE THETIKH_DIAFORA

ARNHTIKH_DIAFORA:
PRINT MINUS
SUB DL,CL
MOV CL,DL
JMP DIAFORA_DONE

THETIKH_DIAFORA: 
SUB CL,DL 

DIAFORA_DONE: 
CMP CL,9
JG DIAFORA_10_EWS_15

DIAFORA_0_EWS_9:
ADD CL,48
PRINT CL
JMP DIAFORA_COMPLETE

DIAFORA_10_EWS_15:
PRINT '1'
ADD CL,-10
ADD CL,48
PRINT CL

DIAFORA_COMPLETE: 
;MAIN EDW SUMPLHRWSW-------------





PRINT_STR NEWLINE
    

    
    JMP START           ;SYNEXHS LEITOURGIA
    
     QUIT:              ;TERMATISMOS
            MOV AH,4CH	;INT 21/4C EINAI GIA TERMATISMO OPWS PREPEI, EPISTREFONTAS VALUE STON AL
            INT 21H
          
        
MAIN ENDP

PRINT_DEC PROC NEAR	 ;typwnei se dekadiko oti uparxei ston BL se bin
		MOV CX,0
		MOV AX,BX
	DA: MOV DX,0
		MOV BX,10
		DIV BX
		PUSH DX
		INC CX
		CMP AX,0
		JNZ DA
	DA2: POP DX
		ADD DX,30H
		PRINT DL
		LOOP DA2
		RET
PRINT_DEC ENDP 
	
	
PRINT_HEX_DIGITS_FROM_AL PROC NEAR    ;PAIRNEI WS ORISMA TON 8-BIT REGISTER AL
    ;KAI TYPWNEI STHN O8ONH TA HEX PSIFIA TOY(1 'H 2). AN TO PRWTO EINAI MHDEN OPWS p.x.
    ;GIA AL=0000 1010=0Ahex TYPWNEI MONO TO A , ENW AN AL=1001 0101=95H TYPWNEI 95
    ;DEN EPHREAZEI KANENAN KATAXWRHTH!!!
    PUSH AX     
    
    ;MSB HEX PSIFIO
    PUSH AX  ;APO8HKEUSE ORIGINAL ARI8MO
    AND AL,11110000b
    CMP AL,0
    JE LSB_HEX_PSIFIO
    ;MH MHDENIKO TO MSB HEX PSIFIO, TO TYPWNOUME!
    ROR AL,4    ;SHIFT 4 8ESEIS DEKSIA XWRIS KRATOUMENO WSTE NA ER8EI STA MSB TO HEX PSIFIO
    CALL 4_BIT_HEX_TO_ASCII   ;ASCII CODING
    PRINT AL
    
    
    LSB_HEX_PSIFIO:
    POP AX  ;KSANAPARE TON ORIGINAL ARI8MO
    AND AL,00001111b
    CALL 4_BIT_HEX_TO_ASCII   ;ASCII CODING
    PRINT AL
    
 
    POP AX    
    RET
PRINT_HEX_DIGITS_FROM_AL ENDP 	                  
	                  
	
ASCII_TO_HEX_BIT PROC NEAR    ;PAIRNEI WS ORISMA ENAN ARI8MO HEX (0-F) APO TO PLHKTROLOGIO 
    ;POU EINAI STON AL APO8HKEUMENOS SE ASCII KAI EPISTREFEI STON AL TO HEX BIT POU DWSAME
 
    CMP AL,48
    JL ERROR    ;EISODOS EKTOS 0-F
    CMP AL,57
    JG A_TO_F
    
    ;0-9    48-57 DEC STON ASCII PINAKA
    SUB AL,48
    JMP JOB_DONE1
    
    A_TO_F:
    CMP AL,65
    JL ERROR    ;EISODOS EKTOS 0-F
    CMP AL,70
    JG ERROR    ;EISODOS EKTOS 0-F
    
    ;A-F    65-70 DEC STON ASCII PINAKA
    SUB AL,55
    JMP JOB_DONE1
    
    
    ERROR:
    PRINT_STR ERRORMSG 
    
    JOB_DONE1:
    ;APOTELESMA STON AL
    RET
ASCII_TO_HEX_BIT ENDP  


4_BIT_HEX_TO_ASCII PROC NEAR
    ;PAIRNEI WS ORISMA TON AL STH MORFH AL=0000 XXXX
    ;KAI EPISTREFEI TON ASCII TOU STON AL PALI
    ;(DOULEUEI GIA TOUS ASCII TWN 0-9 KAI A-F)
    
    CMP AL,9
    JG A_EWS_F
    
    ;0-9
    ADD AL,48
    JMP DONE
    
    A_EWS_F:
    ;A-F
    ADD AL,55
    
    DONE:
    RET
4_BIT_HEX_TO_ASCII ENDP                         
                         
CODE ENDS
END MAIN